# ----
# Site

title: GSoc2021-DBpedia-NeuralExtraction
url: "https://zoenantes.github.io/GSoc2021-DBpedia-NeuralExtraction/"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/siteicon.png
description: The weekly blog for this project
author:
  name: Ziwei XU
  email: xuxiaowei0203@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: GSoc2021
  links:
    - https://github.com/dbpedia/neural-extraction-framework

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:title/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
